main: de.raidcraft.tips.TipsPlugin
name: RCTips
version: ${project.version}#${build.number}
description: Plugin that provides dynamic tips to users.
author: Silthus
website: http://www.raid-craft.de
depend: [RaidCraft-API]
database: true
api-verson: 1.13
permissions:
  rctips.admin:
      description: Grants all admin tips permissions.
      default: false
      children:
        rctips.create: true
        rctips.reload: true